#!/bin/sh
exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

echo "Starting NDR"

# Mount the necessities
mount -t proc none /proc
mount -t sysfs none /sys

# Start udev
UDEV_BIN=/sbin/udevd
test -x $UDEV_BIN || exit 5

clear

# Check for config file and read it
UDEV_CONFIG=/etc/udev/udev.conf
test -r $UDEV_CONFIG || exit 6
. $UDEV_CONFIG

printf '\000\000\000\000' > /proc/sys/kernel/hotplug
$UDEV_BIN -d || (echo "FAIL" && exit 1)
udevadm trigger --type=subsystems --action=add
udevadm trigger --type=devices --action=add
udevadm settle --timeout=30 || echo "udevadm settle failed"

echo "Switching to rootfs"
mount -o ro /dev/disk/by-partlabel/ndr-rootfs /root
exec switch_root /root /sbin/init
