#!/bin/sh -x

. /etc/image.config

#IMAGE_URL="https://archive.securedbythem.casadevall.pro/images/rootfs"

HOST_RANDOM=`cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
HOSTNAME=ndr-$HOST_RANDOM

# dhcpd has some issues with nameservers on early boot, just hardcode in
# Google DNS for now
echo "nameserver 8.8.8.8" > /etc/resolv.conf

trap cleanup INT
function cleanup() {
    echo "=== Cleaning Up ==="
    exit 1
}

function run_or_die() {
    eval $1
    if [ $? -ne 0 ]; then
        echo "BAILING OUT: $1 failed"
        cleanup
    fi
}

case "$1" in
    start)
        # Setup Networking
        run_or_die "dhcpcd -w --oneshot"

        echo "=== Partitioning Installation Drive ==="
        if [ -e /dev/mmcblk0 ]; then
            INSTALLATION_DRIVE=/dev/mmcblk0
            echo "Installing to $INSTALLATION_DRIVE"
        elif [ -e /dev/sda ]; then
            INSTALLATION_DRIVE=/dev/sda
            echo "Installing to /dev/sda"
        else
            echo "No valid installation drive found!, Bailing out!"
        fi

        # Partition the drive
        parted $INSTALLATION_DRIVE --script -- \
            unit MiB \
            mklabel gpt \
            mkpart fat32 1MiB 513MiB \
            mkpart ext4 513MiB 2561MiB \
            mkpart ext4 2561MiB -1MiB \
            set 1 boot on \
            name 1 ndr-esp \
            name 2 ndr-rootfs \
            name 3 ndr-persistant
        partprobe

        # udev race, takes a few moments for it to see the part change
        echo "=== Waiting for udev to see partition changes ==="
        sleep 15

        # Format partitions
        run_or_die "mkfs.ext4 -F $ROOT_PART"
        run_or_die "mkfs.ext4 -F $PERSISTANT_PART"
        run_or_die "mkfs.vfat -F32 $ESP_PART"

        # Make some temporary folders and mount stuff
        mkdir /ESP
        mkdir /persistant
        mkdir /rootfs

        run_or_die "mount $PERSISTANT_PART /persistant"

        # Create the ndr directory for storing the network configuration

        mkdir -p /persistant/etc/ndr
        if [ ! -e "/persistant/etc/hostname" ]; then
            echo "$HOSTNAME" > /persistant/etc/hostname;
        fi

        if [ ! -e "/persistant/etc/hosts" ]; then
            echo "127.0.0.1 localhost" > /persistant/etc/hosts;
            echo "127.0.1.1 $HOSTNAME" >> /persistant/etc/hosts;
            echo "::1 localhost" >> /persistant/etc/hosts;
        fi

        # Configure the hosts and hostname files if they're MIA

        echo "=== Downloading root filesystem ==="
        run_or_die "curl -o /persistant/rootfs.img.bz2 $ROOTFS_IMAGE"
        run_or_die "bzcat /persistant/rootfs.img.bz2 | dd of=$ROOT_PART"
        sync
        sync
        cd /
        run_or_die "umount /persistant"

        echo "=== Installing bootx64.efi ==="
        run_or_die "mount $ESP_PART /ESP"
        mkdir -p /ESP/EFI/boot/
        cd /ESP/EFI/boot/
        run_or_die "curl -o bootx64.efi $BOOT0_IMAGE"
        cd /
	    umount /ESP
        reboot
        ;;
    *)
        echo "Usage: $0 {start}"
        exit 1
        ;;

esac
